spec.js:

/**
 * Express supported markets: one TCID per (language variant x region).
 * Each row includes path; TCIDs 2–130 use `&country={region}` on the URL.
 * @see https://main--da-express-milo--adobecom.aem.page/express/assets/supported-markets/supported-markets-express.json
 * 0-130 = positive market selector cases , 131- 140 
 */

module.exports = {
  name: 'expresslingo',
  features: [
{
      tcid: '0',
      name: '@express-us-supported-markets',
      lang: 'en',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off',
      tags:'@express-lingo @express-us-supported-markets',
    },
{
      tcid: '1',
      name: '@express-non-us-supported-markets',
      lang: 'jp',
      path: 'https://main--da-express-milo--adobecom.aem.live/jp/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off',
      tags: '@express-lingo @express-non-us-supported-markets',
    },

    {
      tcid: '2',
      name: '@express-market-en-ae',
      lang: 'en',
      region: 'ae',
      defaultCurrency: 'United Arab Emirates - AED د.إ',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ae',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ae',
    },
    {
      tcid: '3',
      name: '@express-market-en-am',
      lang: 'en',
      region: 'am',
      defaultCurrency: 'Armenia - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=am',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-am',
    },
    {
      tcid: '4',
      name: '@express-market-en-ar',
      lang: 'en',
      region: 'ar',
      defaultCurrency: 'Argentina - ARS $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ar',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ar',
    },
    {
      tcid: '5',
      name: '@express-market-en-at',
      lang: 'en',
      region: 'at',
      defaultCurrency: 'Austria - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=at',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-at',
    },
    {
      tcid: '6',
      name: '@express-market-en-au',
      lang: 'en',
      region: 'au',
      defaultCurrency: 'Australia - AUD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=au',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-au',
    },
    {
      tcid: '7',
      name: '@express-market-en-az',
      lang: 'en',
      region: 'az',
      defaultCurrency: 'Azerbaijan - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=az',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-az',
    },
    {
      tcid: '8',
      name: '@express-market-en-be',
      lang: 'en',
      region: 'be',
      defaultCurrency: 'Belgium - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=be',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-be',
    },
    {
      tcid: '9',
      name: '@express-market-en-bg',
      lang: 'en',
      region: 'bg',
      defaultCurrency: 'Bulgaria - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=bg',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-bg',
    },
    {
      tcid: '10',
      name: '@express-market-en-bh',
      lang: 'en',
      region: 'bh',
      defaultCurrency: 'Bahrain - BHD .د.ب',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=bh',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-bh',
    },
    {
      tcid: '11',
      name: '@express-market-en-bo',
      lang: 'en',
      region: 'bo',
      defaultCurrency: 'Bolivia - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=bo',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-bo',
    },
    {
      tcid: '12',
      name: '@express-market-en-br',
      lang: 'en',
      region: 'br',
      defaultCurrency: 'Brazil - BRL R$',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=br',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-br',
    },
    {
      tcid: '13',
      name: '@express-market-en-ca',
      lang: 'en',
      region: 'ca',
      defaultCurrency: 'Canada - CAD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ca',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ca',
    },
    {
      tcid: '14',
      name: '@express-market-en-ch',
      lang: 'en',
      region: 'ch',
      defaultCurrency: 'Switzerland - CHF',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ch',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ch',
    },
    {
      tcid: '15',
      name: '@express-market-en-cl',
      lang: 'en',
      region: 'cl',
      defaultCurrency: 'Chile - CLP $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=cl',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-cl',
    },
    {
      tcid: '16',
      name: '@express-market-en-co',
      lang: 'en',
      region: 'co',
      defaultCurrency: 'Colombia - COP $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=co',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-co',
    },
    {
      tcid: '17',
      name: '@express-market-en-cr',
      lang: 'en',
      region: 'cr',
      defaultCurrency: 'Costa Rica - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=cr',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-cr',
    },
    {
      tcid: '18',
      name: '@express-market-en-cy',
      lang: 'en',
      region: 'cy',
      defaultCurrency: 'Cyprus - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=cy',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-cy',
    },
    {
      tcid: '19',
      name: '@express-market-en-cz',
      lang: 'en',
      region: 'cz',
      defaultCurrency: 'Czech Republic - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=cz',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-cz',
    },
    {
      tcid: '20',
      name: '@express-lingo-en-de',
      lang: 'en',
      region: 'de',
      defaultCurrency: 'Germany - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=de',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-de',
    },
    {
      tcid: '21',
      name: '@express-lingo-en-dk',
      lang: 'en',
      region: 'dk',
      defaultCurrency: 'Denmark - DKK kr',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=dk',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-dk',
    },
    {
      tcid: '22',
      name: '@express-lingo-en-do',
      lang: 'en',
      region: 'do',
      defaultCurrency: 'Dominican Republic - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=do',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-do',
    },
    {
      tcid: '23',
      name: '@express-lingo-en-dz',
      lang: 'en',
      region: 'dz',
      defaultCurrency: 'Algeria - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=dz',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-dz',
    },
    {
      tcid: '24',
      name: '@express-lingo-en-ec',
      lang: 'en',
      region: 'ec',
      defaultCurrency: 'Ecuador - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ec',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ec',
    },
    {
      tcid: '25',
      name: '@express-lingo-en-ee',
      lang: 'en',
      region: 'ee',
      defaultCurrency: 'Estonia - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ee',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ee',
    },
    {
      tcid: '26',
      name: '@express-lingo-en-eg',
      lang: 'en',
      region: 'eg',
      defaultCurrency: 'Egypt - EGP £',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=eg',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-eg',
    },
    {
      tcid: '27',
      name: '@express-lingo-en-es',
      lang: 'en',
      region: 'es',
      defaultCurrency: 'Spain - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=es',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-es',
    },
    {
      tcid: '28',
      name: '@express-lingo-en-fi',
      lang: 'en',
      region: 'fi',
      defaultCurrency: 'Finland - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=fi',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-fi',
    },
    {
      tcid: '29',
      name: '@express-lingo-en-fr',
      lang: 'en',
      region: 'fr',
      defaultCurrency: 'France - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=fr',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-fr',
    },
    {
      tcid: '30',
      name: '@express-lingo-en-gb',
      lang: 'en',
      region: 'gb',
      defaultCurrency: 'United Kingdom - GBP £',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=gb',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-gb',
    },
    {
      tcid: '31',
      name: '@express-lingo-en-ge',
      lang: 'en',
      region: 'ge',
      defaultCurrency: 'TEST - ge',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ge',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ge',
    },
    {
      tcid: '32',
      name: '@express-lingo-en-gr',
      lang: 'en',
      region: 'gr',
      defaultCurrency: 'Greece - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=gr',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-gr',
    },
    {
      tcid: '33',
      name: '@express-lingo-en-gt',
      lang: 'en',
      region: 'gt',
      defaultCurrency: 'Guatemala - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=gt',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-gt',
    },
    {
      tcid: '34',
      name: '@express-lingo-en-hk',
      lang: 'en',
      region: 'hk',
      defaultCurrency: 'Hong Kong - HKD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=hk',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-hk',
    },
    {
      tcid: '35',
      name: '@express-lingo-en-hr',
      lang: 'en',
      region: 'hr',
      defaultCurrency: 'Croatia - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=hr',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-hr',
    },
    {
      tcid: '36',
      name: '@express-lingo-en-hu',
      lang: 'en',
      region: 'hu',
      defaultCurrency: 'Hungary - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=hu',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-hu',
    },
    {
      tcid: '37',
      name: '@express-lingo-en-id',
      lang: 'en',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=id',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-id',
    },
    {
      tcid: '38',
      name: '@express-lingo-en-ie',
      lang: 'en',
      region: 'ie',
      defaultCurrency: 'Ireland - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ie',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ie',
    },
    {
      tcid: '39',
      name: '@express-lingo-en-il',
      lang: 'en',
      region: 'il',
      defaultCurrency: 'Israel - ILS ₪',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=il',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-il',
    },
    {
      tcid: '40',
      name: '@express-lingo-en-in',
      lang: 'en',
      region: 'in',
      defaultCurrency: 'India - INR ₹',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=in',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-in',
    },
    {
      tcid: '41',
      name: '@express-lingo-en-it',
      lang: 'en',
      region: 'it',
      defaultCurrency: 'Italy - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=it',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-it',
    },
    {
      tcid: '42',
      name: '@express-lingo-en-jo',
      lang: 'en',
      region: 'jo',
      defaultCurrency: 'Jordan - JOD د.ا',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=jo',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-jo',
    },
    {
      tcid: '43',
      name: '@express-lingo-en-jp',
      lang: 'en',
      region: 'jp',
      defaultCurrency: 'Japan - JPY ¥',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=jp',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-jp',
    },
    {
      tcid: '44',
      name: '@express-lingo-en-ke',
      lang: 'en',
      region: 'ke',
      defaultCurrency: 'Kenya - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ke',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ke',
    },
    {
      tcid: '45',
      name: '@express-lingo-en-kg',
      lang: 'en',
      region: 'kg',
      defaultCurrency: 'Kyrgyzstan - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=kg',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-kg',
    },
    {
      tcid: '46',
      name: '@express-lingo-en-kr',
      lang: 'en',
      region: 'kr',
      defaultCurrency: 'South Korea - KRW ₩',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=kr',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-kr',
    },
    {
      tcid: '47',
      name: '@express-lingo-en-kw',
      lang: 'en',
      region: 'kw',
      defaultCurrency: 'Kuwait - KWD د.ك',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=kw',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-kw',
    },
    {
      tcid: '48',
      name: '@express-lingo-en-kz',
      lang: 'en',
      region: 'kz',
      defaultCurrency: 'Kazakhstan - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=kz',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-kz',
    },
    {
      tcid: '49',
      name: '@express-lingo-en-lb',
      lang: 'en',
      region: 'lb',
      defaultCurrency: 'Lebanon - LBP ل.ل',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=lb',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-lb',
    },
    {
      tcid: '50',
      name: '@express-lingo-en-lk',
      lang: 'en',
      region: 'lk',
      defaultCurrency: 'Sri Lanka - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=lk',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-lk',
    },
    {
      tcid: '51',
      name: '@express-lingo-en-lt',
      lang: 'en',
      region: 'lt',
      defaultCurrency: 'Lithuania - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=lt',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-lt',
    },
    {
      tcid: '52',
      name: '@express-lingo-en-lu',
      lang: 'en',
      region: 'lu',
      defaultCurrency: 'Luxembourg - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=lu',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-lu',
    },
    {
      tcid: '53',
      name: '@express-lingo-en-lv',
      lang: 'en',
      region: 'lv',
      defaultCurrency: 'Latvia - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=lv',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-lv',
    },
    {
      tcid: '54',
      name: '@express-lingo-en-ma',
      lang: 'en',
      region: 'ma',
      defaultCurrency: 'Morocco - MAD د.م.',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ma',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ma',
    },
    {
      tcid: '55',
      name: '@express-lingo-en-md',
      lang: 'en',
      region: 'md',
      defaultCurrency: 'Moldova - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=md',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-md',
    },
    {
      tcid: '56',
      name: '@express-lingo-en-mo',
      lang: 'en',
      region: 'mo',
      defaultCurrency: 'Macau - HKD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=mo',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-mo',
    },
    {
      tcid: '57',
      name: '@express-lingo-en-mt',
      lang: 'en',
      region: 'mt',
      defaultCurrency: 'Malta - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=mt',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-mt',
    },
    {
      tcid: '58',
      name: '@express-lingo-en-mu',
      lang: 'en',
      region: 'mu',
      defaultCurrency: 'Mauritius - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=mu',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-mu',
    },
    {
      tcid: '59',
      name: '@express-lingo-en-mx',
      lang: 'en',
      region: 'mx',
      defaultCurrency: 'Mexico - MXN $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=mx',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-mx',
    },
    {
      tcid: '60',
      name: '@express-lingo-en-my',
      lang: 'en',
      region: 'my',
      defaultCurrency: 'Malaysia - MYR RM',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=my',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-my',
    },
    {
      tcid: '61',
      name: '@express-lingo-en-ng',
      lang: 'en',
      region: 'ng',
      defaultCurrency: 'Nigeria - NGN ₦',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ng',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ng',
    },
    {
      tcid: '62',
      name: '@express-lingo-en-nl',
      lang: 'en',
      region: 'nl',
      defaultCurrency: 'Netherlands - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=nl',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-nl',
    },
    {
      tcid: '63',
      name: '@express-lingo-en-no',
      lang: 'en',
      region: 'no',
      defaultCurrency: 'Norway - NOK kr',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=no',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-no',
    },
    {
      tcid: '64',
      name: '@express-lingo-en-nz',
      lang: 'en',
      region: 'nz',
      defaultCurrency: 'New Zealand - NZD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=nz',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-nz',
    },
    {
      tcid: '65',
      name: '@express-lingo-en-om',
      lang: 'en',
      region: 'om',
      defaultCurrency: 'Oman - OMR ر.ع.',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=om',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-om',
    },
    {
      tcid: '66',
      name: '@express-lingo-en-pa',
      lang: 'en',
      region: 'pa',
      defaultCurrency: 'Panama - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=pa',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-pa',
    },
    {
      tcid: '67',
      name: '@express-lingo-en-pe',
      lang: 'en',
      region: 'pe',
      defaultCurrency: 'Peru - PEN S/',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=pe',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-pe',
    },
    {
      tcid: '68',
      name: '@express-lingo-en-ph',
      lang: 'en',
      region: 'ph',
      defaultCurrency: 'Philippines - PHP ₱',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ph',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ph',
    },
    {
      tcid: '69',
      name: '@express-lingo-en-pl',
      lang: 'en',
      region: 'pl',
      defaultCurrency: 'Poland - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=pl',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-pl',
    },
    {
      tcid: '70',
      name: '@express-lingo-en-pt',
      lang: 'en',
      region: 'pt',
      defaultCurrency: 'Portugal - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=pt',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-pt',
    },
    {
      tcid: '71',
      name: '@express-lingo-en-py',
      lang: 'en',
      region: 'py',
      defaultCurrency: 'Paraguay - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=py',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-py',
    },
    {
      tcid: '72',
      name: '@express-lingo-en-qa',
      lang: 'en',
      region: 'qa',
      defaultCurrency: 'Qatar - QAR ر.ق',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=qa',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-qa',
    },
    {
      tcid: '73',
      name: '@express-lingo-en-ro',
      lang: 'en',
      region: 'ro',
      defaultCurrency: 'Romania - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ro',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ro',
    },
    {
      tcid: '74',
      name: '@express-lingo-en-sa',
      lang: 'en',
      region: 'sa',
      defaultCurrency: 'Saudi Arabia - SAR ﷼',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=sa',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-sa',
    },
    {
      tcid: '75',
      name: '@express-lingo-en-se',
      lang: 'en',
      region: 'se',
      defaultCurrency: 'Sweden - SEK kr',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=se',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-se',
    },
    {
      tcid: '76',
      name: '@express-lingo-en-sg',
      lang: 'en',
      region: 'sg',
      defaultCurrency: 'Singapore - SGD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=sg',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-sg',
    },
    {
      tcid: '77',
      name: '@express-lingo-en-si',
      lang: 'en',
      region: 'si',
      defaultCurrency: 'Slovenia - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=si',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-si',
    },
    {
      tcid: '78',
      name: '@express-lingo-en-sk',
      lang: 'en',
      region: 'sk',
      defaultCurrency: 'Slovakia - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=sk',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-sk',
    },
    {
      tcid: '79',
      name: '@express-lingo-en-sv',
      lang: 'en',
      region: 'sv',
      defaultCurrency: 'Sweden - SEK kr',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=sv',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-sv',
    },
    {
      tcid: '80',
      name: '@express-lingo-en-th',
      lang: 'en',
      region: 'th',
      defaultCurrency: 'Thailand - THB ฿',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=th',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-th',
    },
    {
      tcid: '81',
      name: '@express-lingo-en-tj',
      lang: 'en',
      region: 'tj',
      defaultCurrency: 'Tajikistan - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=tj',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-tj',
    },
    {
      tcid: '82',
      name: '@express-lingo-en-tm',
      lang: 'en',
      region: 'tm',
      defaultCurrency: 'Turkmenistan - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=tm',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-tm',
    },
    {
      tcid: '83',
      name: '@express-lingo-en-tn',
      lang: 'en',
      region: 'tn',
      defaultCurrency: 'Tunisia - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=tn',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-tn',
    },
    {
      tcid: '84',
      name: '@express-lingo-en-tr',
      lang: 'en',
      region: 'tr',
      defaultCurrency: 'Türkiye - TRY ₺',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=tr',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-tr',
    },
    {
      tcid: '85',
      name: '@express-lingo-en-tt',
      lang: 'en',
      region: 'tt',
      defaultCurrency: 'Trinidad and Tobago - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=tt',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-tt',
    },
    {
      tcid: '86',
      name: '@express-lingo-en-tw',
      lang: 'en',
      region: 'tw',
      defaultCurrency: 'Taiwan - TWD NT$',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=tw',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-tw',
    },
    {
      tcid: '87',
      name: '@express-lingo-en-ua',
      lang: 'en',
      region: 'ua',
      defaultCurrency: 'Ukraine - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ua',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ua',
    },
    {
      tcid: '88',
      name: '@express-lingo-en-us',
      lang: 'en',
      region: 'us',
      defaultCurrency: 'United States - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=us',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-us',
    },
    {
      tcid: '89',
      name: '@express-lingo-en-uy',
      lang: 'en',
      region: 'uy',
      defaultCurrency: 'Uruguay - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=uy',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-uy',
    },
    {
      tcid: '90',
      name: '@express-lingo-en-uz',
      lang: 'en',
      region: 'uz',
      defaultCurrency: 'Uzbekistan - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=uz',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-uz',
    },
    {
      tcid: '91',
      name: '@express-lingo-en-ve',
      lang: 'en',
      region: 've',
      defaultCurrency: 'Venezuela - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=ve',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-ve',
    },
    {
      tcid: '92',
      name: '@express-lingo-en-vn',
      lang: 'en',
      region: 'vn',
      defaultCurrency: 'Vietnam - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=vn',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-vn',
    },
    {
      tcid: '93',
      name: '@express-lingo-en-za',
      lang: 'en',
      region: 'za',
      defaultCurrency: 'South Africa - ZAR R',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/drafts/lingo/selector-market?milolibs=acommarketselector&languageBanner=off&country=za',
      tags:
        '@express-lingo @express-market @express-language-en @express-english-za',
    },
    {
      tcid: '94',
      name: '@express-lingo-uk-gb',
      lang: 'en_uk',
      region: 'gb',
      defaultCurrency: 'United Kingdom - GBP £',
      path: 'https://main--da-express-milo--adobecom.aem.live/uk/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=gb',
      tags: '@express-lingo @express-market @express-language-en-gb @express-english-gb',
    },
    {
      tcid: '95',
      name: '@express-lingo-in-in',
      lang: 'en_in',
      region: 'in',
      defaultCurrency: 'India - INR ₹',
      path: 'https://main--da-express-milo--adobecom.aem.live/in/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=in',
      tags: '@express-lingo @express-market @express-language-en-in @express-english-in',
    },
    {
      tcid: '96',
      name: '@express-market-fr-be',
      lang: 'fr',
      region: 'be',
      defaultCurrency: 'Belgium - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/fr/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=be',
      tags: '@express-lingo @express-market @express-language-fr @express-french-be',
    },
    {
      tcid: '97',
      name: '@express-market-fr-ca',
      lang: 'fr',
      region: 'ca',
      defaultCurrency: 'Canada - CAD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/fr/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=ca',
      tags: '@express-lingo @express-market @express-language-fr @express-french-ca',
    },
    {
      tcid: '98',
      name: '@express-market-fr-fr',
      lang: 'fr',
      region: 'fr',
      defaultCurrency: 'France - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/fr/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=fr',
      tags: '@express-lingo @express-market @express-language-fr @express-french-fr',
    },
    {
      tcid: '99',
      name: '@express-market-fr-ch',
      lang: 'fr',
      region: 'ch',
      defaultCurrency: 'Switzerland - CHF',
      path: 'https://main--da-express-milo--adobecom.aem.live/fr/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=ch',
      tags: '@express-lingo @express-market @express-language-fr @express-french-ch',
    },
    {
      tcid: '100',
      name: '@express-market-fr-lu',
      lang: 'fr',
      region: 'lu',
      defaultCurrency: 'Luxembourg - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/fr/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=lu',
      tags: '@express-lingo @express-market @express-language-fr @express-french-lu',
    },
    {
      tcid: '101',
      name: '@express-market-de-at',
      lang: 'de',
      region: 'at',
      defaultCurrency: 'Österreich - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/de/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=at',
      tags: '@express-lingo @express-market @express-language-de @express-german-at',
    },
    {
      tcid: '102',
      name: '@express-market-de-de',
      lang: 'de',
      region: 'de',
      defaultCurrency: 'Deutschland - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/de/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=de',
      tags: '@express-lingo @express-market @express-language-de @express-german-de',
    },
    {
      tcid: '103',
      name: '@express-market-de-lu',
      lang: 'de',
      region: 'lu',
      defaultCurrency: 'Luxemburg - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/de/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=lu',
      tags: '@express-lingo @express-market @express-language-de @express-german-lu',
    },
    {
      tcid: '104',
      name: '@express-market-de-ch',
      lang: 'de',
      region: 'ch',
      defaultCurrency: 'Schweiz - CHF',
      path: 'https://main--da-express-milo--adobecom.aem.live/de/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=ch',
      tags: '@express-lingo @express-market @express-language-de @express-german-ch',
    },
    {
      tcid: '105',
      name: '@express-lingo-ja-jp',
      lang: 'ja',
      region: 'jp',
      defaultCurrency: '日本 - JPY ¥',
      path: 'https://main--da-express-milo--adobecom.aem.live/jp/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=jp',
      tags: '@express-lingo @express-market @express-language-ja @express-japanese-jp',
    },
    {
      tcid: '106',
      name: '@express-lingo-es-ar',
      lang: 'es',
      region: 'ar',
      defaultCurrency: 'Argentina - ARS $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=ar',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-ar',
    },
    {
      tcid: '107',
      name: '@express-lingo-es-cl',
      lang: 'es',
      region: 'cl',
      defaultCurrency: 'Chile - CLP $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=cl',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-cl',
    },
    {
      tcid: '108',
      name: '@express-lingo-es-co',
      lang: 'es',
      region: 'co',
      defaultCurrency: 'Colombia - COP $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=co',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-co',
    },
    {
      tcid: '109',
      name: '@express-lingo-es-cr',
      lang: 'es',
      region: 'cr',
      defaultCurrency: 'Costa Rica - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=cr',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-cr',
    },
    {
      tcid: '110',
      name: '@express-lingo-es-ec',
      lang: 'es',
      region: 'ec',
      defaultCurrency: 'Ecuador - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=ec',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-ec',
    },
    {
      tcid: '111',
      name: '@express-lingo-es-es',
      lang: 'es',
      region: 'es',
      defaultCurrency: 'España - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=es',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-es',
    },
    {
      tcid: '112',
      name: '@express-lingo-es-gt',
      lang: 'es',
      region: 'gt',
      defaultCurrency: 'Guatemala - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=gt',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-gt',
    },
    {
      tcid: '113',
      name: '@express-lingo-es-mx',
      lang: 'es',
      region: 'mx',
      defaultCurrency: 'México - MXN $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=mx',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-mx',
    },
    {
      tcid: '114',
      name: '@express-lingo-es-pe',
      lang: 'es',
      region: 'pe',
      defaultCurrency: 'Perú - PEN S/',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=pe',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-pe',
    },
    {
      tcid: '115',
      name: '@express-lingo-es-pr',
      lang: 'es',
      region: 'pr',
      defaultCurrency: 'Estados Unidos - USD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/es/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=pr',
      tags: '@express-lingo @express-market @express-language-es @express-spanish-pr',
    },
    {
      tcid: '116',
      name: '@express-lingo-ko-kr',
      lang: 'ko',
      region: 'kr',
      defaultCurrency: 'South Korea - KRW ₩',
      path: 'https://main--da-express-milo--adobecom.aem.live/kr/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=kr',
      tags: '@express-lingo @express-market @express-language-ko @express-korean-kr',
    },
    {
      tcid: '117',
      name: '@express-lingo-it-it',
      lang: 'it',
      region: 'it',
      defaultCurrency: 'Italy - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/it/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=it',
      tags: '@express-lingo @express-market @express-language-it @express-italian-it',
    },
    {
      tcid: '118',
      name: '@express-lingo-it-ch',
      lang: 'it',
      region: 'ch',
      defaultCurrency: 'Switzerland - CHF',
      path: 'https://main--da-express-milo--adobecom.aem.live/it/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=ch',
      tags: '@express-lingo @express-market @express-language-it @express-italian-ch',
    },
    {
      tcid: '119',
      name: '@express-lingo-pt-br',
      lang: 'pt',
      region: 'br',
      defaultCurrency: 'Brasil - BRL R$',
      path: 'https://main--da-express-milo--adobecom.aem.live/br/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=br',
      tags: '@express-lingo @express-market @express-language-pt @express-portuguese-br',
    },
    {
      tcid: '120',
      name: '@express-lingo-pt-pt',
      lang: 'pt',
      region: 'pt',
      defaultCurrency: 'Portugal - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/br/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=pt',
      tags: '@express-lingo @express-market @express-language-pt @express-portuguese-pt',
    },
    {
      tcid: '121',
      name: '@express-lingo-nl-be',
      lang: 'nl',
      region: 'be',
      defaultCurrency: 'Belgium - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/nl/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=be',
      tags: '@express-lingo @express-market @express-language-nl @express-dutch-be',
    },
    {
      tcid: '122',
      name: '@express-lingo-nl-nl',
      lang: 'nl',
      region: 'nl',
      defaultCurrency: 'Nederland - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/nl/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=nl',
      tags: '@express-lingo @express-market @express-language-nl @express-dutch-nl',
    },
    {
      tcid: '123',
      name: '@express-lingo-zh-hk',
      lang: 'zh',
      region: 'hk',
      defaultCurrency: '香港 - HKD $',
      path: 'https://main--da-express-milo--adobecom.aem.live/tw/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=hk',
      tags: '@express-lingo @express-market @express-language-zh-hk @express-chinese-hk',
    },
    {
      tcid: '124',
      name: '@express-lingo-zh-tw',
      lang: 'zh',
      region: 'tw',
      defaultCurrency: 'Taiwan - TWD NT$',
      path: 'https://main--da-express-milo--adobecom.aem.live/tw/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=tw',
      tags: '@express-lingo @express-market @express-language-zh-hk @express-chinese-tw',
    },
    {
      tcid: '125',
      name: '@express-lingo-zh-cn',
      lang: 'zh',
      region: 'cn',
      defaultCurrency: '中国 - CNY ¥',
      path: 'https://main--da-express-milo--adobecom.aem.live/cn/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=cn',
      tags: '@express-lingo @express-market @express-language-zh-cn @express-chinese-cn',
    },
    {
      tcid: '126',
      name: '@express-lingo-da-dk',
      lang: 'da',
      region: 'dk',
      defaultCurrency: 'Denmark - DKK kr',
      path: 'https://main--da-express-milo--adobecom.aem.live/dk/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=dk',
      tags: '@express-lingo @express-market @express-language-da @express-danish-dk',
    },
    {
      tcid: '127',
      name: '@express-lingo-fi-fi',
      lang: 'fi',
      region: 'fi',
      defaultCurrency: 'Suomi - EUR €',
      path: 'https://main--da-express-milo--adobecom.aem.live/fi/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=fi',
      tags: '@express-lingo @express-market @express-language-fi @express-finnish-fi',
    },
    {
      tcid: '128',
      name: '@express-lingo-no-no',
      lang: 'no',
      region: 'no',
      defaultCurrency: 'Norge - NOK kr',
      path: 'https://main--da-express-milo--adobecom.aem.live/no/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=no',
      tags: '@express-lingo @express-market @express-language-no @express-norwegian-no',
    },
    {
      tcid: '129',
      name: '@express-lingo-sv-sv',
      lang: 'sv',
      region: 'sv',
      defaultCurrency: 'Sverige - SEK kr',
      path: 'https://main--da-express-milo--adobecom.aem.live/se/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=sv',
      tags: '@express-lingo @express-market @express-language-sv @express-swedish-sv',
    },
    {
      tcid: '130',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=id',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },

    //-------------------------------------------------Negative Scenarios---------------------------------------------------------------------------------------------------
   /* {
      tcid: '131',
      name: '@express-lingo-en-id',
      lang: 'en',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/express/fragments/drafts/lingo/test/testpage?milolibs=acommarketselector&languageBanner=off&country=br',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },
   {
      tcid: '132',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },
    {
      tcid: '133',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },
    {
      tcid: '134',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },

   {
      tcid: '135',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },
    {
      tcid: '136',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },
  {
      tcid: '137',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },

  {
      tcid: '138',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },
  {
      tcid: '139',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },
  {
      tcid: '140',
      name: '@express-lingo-id-id',
      lang: 'id',
      region: 'id',
      defaultCurrency: 'Indonesia - IDR Rp',
      path: 'https://main--da-express-milo--adobecom.aem.live/id/express/fragments/drafts/lingo/test/testpage?marketsSource=express&milolibs=acommarketselector&languageBanner=on',
      tags: '@express-lingo @express-market @express-language-id @express-indonesian-id',
    },

//-------------------------------------------------------------------------------------------------------------------------------------------------------
  */
],
};



